- name: downloading mongodb repo
  ansible.builtin.template:
    src: mongodb.repo
    dest: /etc/yum.repos.d/momgodb.repo

- name: Install mongodb
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: latest

- name: Loading Schema
  ansible.builtin.shell: mongo --host mongodb-dev.venkata.cloud </app/schema/{{ component }}.js